language: python

matrix:
  include:
    - python: 2.7
    - python: 3.7
    - python: 3.8
    - python: pypy
      env: OPTIONAL=1

before_install:
- wget https://github.com/DiamondLightSource/ispyb-database/releases/download/v1.10.4/ispyb-database-1.10.4.tar.gz
- tar xvfz ispyb-database-1.10.4.tar.gz
- mysql_upgrade -u root
- mysql -u root -e "CREATE DATABASE ispybtest; SET GLOBAL log_bin_trust_function_creators=ON;"
- mysql -u root -D ispybtest < schema/tables.sql
- mysql -u root -D ispybtest < schema/lookups.sql
- mysql -u root -D ispybtest < schema/data.sql
- mysql -u root -D ispybtest < schema/routines.sql
- mysql -u root -D ispybtest < grants/ispyb_processing.sql
- mysql -u root -D ispybtest < grants/ispyb_import.sql
- mysql -u root -e "CREATE USER ispyb_api@'localhost' IDENTIFIED BY 'password_1234'; GRANT ispyb_processing to ispyb_api@'localhost'; GRANT ispyb_import to ispyb_api@'localhost'; SET DEFAULT ROLE ispyb_processing FOR ispyb_api@'localhost';"
- mysql -u root -e "CREATE USER ispyb_api_future@'localhost' IDENTIFIED BY 'password_4321'; GRANT SELECT ON ispybtest.* to ispyb_api_future@'localhost';"

install:
- pip install requirements.txt

script:
- gunicorn ispyb:server

