language: python

matrix:
  include:
    - python: 3.7
      #    - python: pypy
      #env: OPTIONAL=1

addons:
  mariadb: 10.3
  

install:
        - sudo apt-get install -y python3-mysqldb
        - pip install -r requirements.txt 
        - pip install -r tests/requirements.txt 

script:
        - cp ispyb_core_config_example.yml ispyb_core_config.yml
        - cp ispyb_ssx_config_example.yml ispyb_ssx_config.yml
        - cd scripts
        - bash create_db.sh
        - bash run_all.sh
        - cd ..
        - pylint -E app ispyb_core ispyb_ssx
        - coverage run -m pytest
        

after_success:
        - codecov
        - bash <(curl -s https://codecov.io/bash)
#        - bash <(curl -Ls https://coverage.codacy.com/get.sh)
